/* Generated By:JavaCC: Do not edit this line. MathExParserTreeConstants.java Version 5.0 */
package com.dragoonsaga.mathex.parser;

public interface MathExParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTADD = 1;
  public int JJTSUB = 2;
  public int JJTMUL = 3;
  public int JJTDIV = 4;
  public int JJTEXP = 5;
  public int JJTVOID = 6;
  public int JJTNEG = 7;
  public int JJTCONSTANT = 8;
  public int JJTVARIABLE = 9;


  public String[] jjtNodeName = {
    "Start",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Exp",
    "void",
    "Neg",
    "Constant",
    "Variable",
  };
}
/* JavaCC - OriginalChecksum=a77ca4027167c3ea1939f45d9bd6c11b (do not edit this line) */
