/* Generated By:JavaCC: Do not edit this line. MathExParserVisitor.java Version 5.0 */
package com.dragoonsaga.mathex.parser;

public interface MathExParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTSub node, Object data);
  public Object visit(ASTMul node, Object data);
  public Object visit(ASTDiv node, Object data);
  public Object visit(ASTExp node, Object data);
  public Object visit(ASTConstant node, Object data);
  public Object visit(ASTVariable node, Object data);
  public Object visit(DerivitaveNode node, Object data);
}
/* JavaCC - OriginalChecksum=2098e7dbea50d11f08570275d93c5e39 (do not edit this line) */
