/* Generated By:JJTree&JavaCC: Do not edit this line. MathExParserConstants.java */
package com.dragoonsaga.mathex.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MathExParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WS = 1;
  /** RegularExpression Id. */
  int LB = 2;
  /** RegularExpression Id. */
  int lparen = 5;
  /** RegularExpression Id. */
  int rparen = 6;
  /** RegularExpression Id. */
  int eq = 7;
  /** RegularExpression Id. */
  int ne = 8;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 9;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 10;
  /** RegularExpression Id. */
  int HEX_LITERAL = 11;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 12;
  /** RegularExpression Id. */
  int dot = 13;
  /** RegularExpression Id. */
  int IDENTIFIER = 14;
  /** RegularExpression Id. */
  int LETTER = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WS>",
    "<LB>",
    "<token of kind 3>",
    "<token of kind 4>",
    "\"(\"",
    "\")\"",
    "\"==\"",
    "\"!=\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "\"\\\\.\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
  };

}
