/* Generated By:JavaCC: Do not edit this line. MathExParserTreeConstants.java Version 5.0 */
package com.dragoonsaga.mathex.parser;

public interface MathExParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTADD = 1;
  public int JJTSUB = 2;
  public int JJTMUL = 3;
  public int JJTDIV = 4;
  public int JJTEXP = 5;
  public int JJTVOID = 6;
  public int JJTCONSTANT = 7;
  public int JJTVARIABLE = 8;


  public String[] jjtNodeName = {
    "Start",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Exp",
    "void",
    "Constant",
    "Variable",
  };
}
/* JavaCC - OriginalChecksum=29558e2e45fb70a512c47e37e52d3e45 (do not edit this line) */
